transport/nats/nats.go, transport/rabbitmq/rabbitmq.go
Remove hacks for the transport and make them truly bidirectional.
=> Add streaming support to transports

registry/eureka/eureka.go, registry/eureka/marshalling.go, registry/eureka/watcher.go
This is a eureka registry plugin using github.com/hudl/fargo. Currently running into some issues due to https://github.com/hudl/fargo/issues/29. Help welcome otherwise will finish soon.
=> Eureka Registry Plugin

registry/kubernetes/README.md, registry/kubernetes/client/client.go, registry/kubernetes/client/http.go, registry/kubernetes/client/utils.go, registry/kubernetes/client/watch.go, registry/kubernetes/kubernetes.go, registry/kubernetes/kubernetes_test.go, registry/kubernetes/watcher.go
This is what I have managed to achieve with the kubernetes registry so far. Follows on from #14.
There is a Readme with further info.
This is my first major Go contribution, so I'm not expecting my code to be perfect, if there are problems let me know.
Some things that need further work...
- Ports - Currently picking the first one exposed by the k8s service.
- Namespace config option
- Connecting to the API outside of K8s.
- More Tests & real life testing
Just in time for Line of Duty.
=> adding kubernetes registry

broker/nats/nats.go, transport/nats/nats.go
Replace two missing import path.
=> Replace nats package import path

registry/zookeeper/zookeeper.go
https://github.com/micro/go-plugins/pull/24#issuecomment-219397600
This works exactly as in the consul registry.
=> only reregister if service is changed

registry/etcdv3/etcdv3.go, registry/etcdv3/watcher.go
etcdv3 registry backend :)
the watcher is not fully working at the moment. I need to find a way to get the service on a delete event.
I will complete this tomorrow.
=> etcdv3 registry

registry/etcd/etcd.go, registry/etcdv3/etcdv3.go
switched filepath.Join to path.Join to prevent errors on windows.
=> filepath.Join -> path.Join

registry/eureka/eureka.go, registry/eureka/eureka_test.go, registry/eureka/options.go, registry/eureka/options_test.go
Now that the fargo PR has been merged... 
Let me know what you think.
=> Allow for OAuth2 client credentials flow

codec/msgpackrpc/README.md, codec/msgpackrpc/codec.go, codec/msgpackrpc/rpc.go, codec/msgpackrpc/rpc_test.go
Signed-off-by: Byron Ruth <b@devel.io>
=> Implement msgpackrpc codec

broker/redis/README.md, broker/redis/options.go, broker/redis/redis.go, broker/redis/redis_test.go
Signed-off-by: Byron Ruth <b@devel.io>
=> Implement broker for redis

transport/nats/nats.go, transport/rabbitmq/rabbitmq.go
This adds deadline support for connectionless transports.
=> Add deadline support for transport

client/grpc/buffer.go, client/grpc/codec.go, client/grpc/grpc.go, client/grpc/grpc_test.go, client/grpc/publication.go, client/grpc/request.go, client/grpc/stream.go
=> GRPC Client

registry/kubernetes/client/client.go
Added mechanism to detect current k8s namespace from service account secret
=> [registry: kubernetes] Detect pod namespace

client/grpc/grpc.go, server/grpc/buffer.go, server/grpc/codec.go, server/grpc/debug.go, server/grpc/extractor.go, server/grpc/extractor_test.go, server/grpc/grpc.go, server/grpc/grpc_test.go, server/grpc/handler.go, server/grpc/options.go, server/grpc/request.go, server/grpc/server.go, server/grpc/stream.go, server/grpc/subscriber.go, server/grpc/util.go
A grpc server that's compatible with go-micro
=> grpc server

trace/zipkin/zipkin.go
I didn't find my zipkin's service's IP in the call chains until I updated the code.
=> set ipv4 with registry's ip address

micro/bot/input/discord/README.md, micro/bot/input/discord/conn.go, micro/bot/input/discord/discord.go
* pull @zet4's bot/input/discord to go-plugins
add a small README incl. credits
=> add bot input for Discord

micro/bot/input/telegram/README.md, micro/bot/input/telegram/conn.go, micro/bot/input/telegram/telegram.go
```
$ micro bot --inputs=telegram --telegram_token=BOT_TOKEN --telegram_whitelist=COMMA_SEPARATED_NICKNAMES_WITHOUT_AT_SYMBOL
```
=> [micro][bot] Telegram Messenger support

broker/nats/nats.go
Fixes issue #100 
Simply added method for setAddrs() and called it both in Init and NewBroker
=> fixed setting of address through Init() function. Resolving issue #100

broker/nats/nats.go, broker/nats/nats_test.go
* Added test for issue #100
* Updated address to return real connection address if connection has been made.
=> Added test for issue #100

wrapper/trace/opentracing/opentracing.go
moved things around to make things clean and simple
=> added tracing for publish/subcriber

broker/rabbitmq/channel.go, broker/rabbitmq/connection.go, broker/rabbitmq/options.go, broker/rabbitmq/rabbitmq.go
The current implementation lacks the support for headers when subscribing to a queue. I've added support for them, hopefully the implementation is sufficient. Please note that this might be a minor breaking change because it changes the argument list of some functions.
Any feedback is greatly appreciated.
=> Add support for RabbitMQ headers exchange

client/grpc/grpc.go, client/grpc/options.go, server/grpc/grpc.go, server/grpc/options.go
Added an option to configure mutual TLS authentication with gRPC
=> Adding TLS authentication  support for gRPC.

transport/nats/nats.go, transport/nats/nats_test.go
Hi, 
as discussed on Slack, the current implementation of the nats transport can not be used with the `named selector`.
**Background:**
When a client uses the `named selector`, the `named selector` uses the server's address to call a remote method on the server. This assumes that the server is listening on the address (nats subject).
With the current implementation, the nats.Transport always assigns a random string (`nats.NewInbox()`) as the server's address. Therefore the named selector will not work with the current implementation of the nats transport.
This PR tries to solve this issue:
- When no address is set and hence the `server.DefaultAddress` is passed into the Listen function, a random address string is generated.
- When a server address is  set, this server address will be …
=> use the addr parameter of the Listen method (needed for usage with named selector)

broker/sqs/sqs.go
move aws session and sqs client creation to Connect() method of broker
=> https://github.com/micro/go-plugins/issues/129#issuecomment-343162786

broker/kafka/kafka.go
Avoid crash on disconnection
Resolves #145 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/micro/go-plugins/147)
=> kafka: allow multi topic subscriptions

broker/rabbitmq/rabbitmq.go
Fix rabbitmq broker initialization described in #151 
With this changes it will possible to change broker address and exchange after creation.
=> fix rabbitmq initialization

micro/cors/README.md, micro/cors/cors.go
Added a README file, plus removed the `func init() {}`, that shouldn't happen within the plugin itself.
=> ADDED a README file

server/grpc/grpc.go, server/grpc/options.go
=> Add http2 transport option for grpc server

broker/stomp/context.go, broker/stomp/options.go, broker/stomp/publication.go, broker/stomp/stomp.go, broker/stomp/subscriber.go
Added new stomp (STOMP using https://github.com/go-stomp/stomp) broker
=> STOMP broker

selector/named/README.md
=> fix example

broker/nsq/nsq.go, broker/nsq/options.go
Lookupd is is important for dynamically adjusting nsqd nodes.
=> support lookupd, AsyncPublish, DeferredPublish

client/grpc/grpc.go, client/grpc/stream.go
=> fixing lock contention for grpc client stream

broker/nats/nats.go
Resolve https://github.com/micro/go-plugins/issues/218
=> Make nats reusable after disconnection

broker/rabbitmq/channel.go, broker/rabbitmq/connection.go, broker/rabbitmq/connection_test.go, broker/rabbitmq/options.go, broker/rabbitmq/rabbitmq.go
* Broker options
* example := rabbitmq.NewBroker(
rabbitmq.PrefetchCount(1),
rabbitmq.PrefetchGlobal(),
)
=> RabbitMQ prefetch count and global flag

server/grpc/codec.go, server/grpc/error.go, server/grpc/grpc.go, server/grpc/grpc_test.go, server/grpc/options.go, server/grpc/stream.go, server/grpc/util.go
This moves back to using the default grpc server
=> Use default grpc server

broker/googlepubsub/googlepubsub.go, broker/kafka/kafka.go, broker/nsq/nsq.go, broker/rabbitmq/channel.go, micro/trace/uuid/uuid.go, registry/gossip/gossip.go, registry/memory/memory.go, transport/rabbitmq/channel.go, transport/rabbitmq/rabbitmq.go
Internally, "pborman/uuid.NewUUID()" is calling "google/uuid.New()"
that return nil when there is an error [1].
Both package use the same license.
[1] https://github.com/pborman/uuid/blob/master/version1.go#L17
=> all: use single uuid package

server/http/buffer.go, server/http/extractor.go, server/http/http.go, server/http/message.go, server/http/options.go, server/http/subscriber.go
The subscriber code is borrowed from rpc server in go-micro.
=> http server supports subscriber

server/http/extractor.go, server/http/http.go, server/http/http_test.go
Server needs to connect broker when starting and disconnect broker after stoping.
=> fix: connect and disconnect broker

broker/kafka/context.go, broker/kafka/options.go, broker/nats/context.go, broker/nats/nats.go, broker/nats/options.go, broker/rabbitmq/context.go, broker/rabbitmq/options.go, broker/rabbitmq/rabbitmq.go, broker/stan/stan.go, broker/stomp/options.go, broker/stomp/stomp.go
=> propagate context and SuccessAutoAck option other brokers

wrapper/monitoring/prometheus/prometheus.go, wrapper/monitoring/prometheus/prometheus_test.go
=> assign service metadata to prometheus labels

broker/stan/options.go, broker/stan/stan.go
=> broker: stan add Reconnect and Timeout

broker/stan/options.go, broker/stan/stan.go
=> broker: [stan] rework option naming, fix messages

broker/rabbitmq/channel.go, broker/rabbitmq/connection.go, broker/rabbitmq/options.go, broker/rabbitmq/rabbitmq.go
Added support for RabbitMQ Queue Arguments (See https://www.rabbitmq.com/queues.html#optional-arguments for details)
=> Added support for RabbitMQ queue arguments

server/http/http.go
Connecting to broker before registering.
=> fix: The ip:port of Broker is not registered.

wrapper/breaker/gobreaker/gobreaker.go, wrapper/breaker/gobreaker/gobreaker_test.go
=> update gobreaker wrapper to allow multiservice breaker

wrapper/breaker/gobreaker/gobreaker.go
=> gobreaker: fix error parsing

go.mod, go.sum, wrapper/trace/datadog/datadog.go, wrapper/trace/datadog/datadog_test.go, wrapper/trace/datadog/ext.go, wrapper/trace/datadog/helper.go, wrapper/trace/datadog/stats.go, wrapper/trace/datadog/status.go, wrapper/trace/datadog/tracker.go
This pull requests add wrapper for datadog.
the DataDog wrapper has been tested for 30 days without any issue.
=> datadog trace wrapper

wrapper/trace/opentracing/opentracing.go
this pull request fix race condition in opentracing wrapper
=> fix race condition

wrapper/ratelimiter/uber/uber.go
=> wrapper/ratelimiter/uber: export options

client/grpc/error.go
fix https://github.com/micro/go-micro/issues/438
=> convert grpc error to micro InternalServerError

wrapper/trace/opentracing/opentracing.go, wrapper/trace/opentracing/opentracing_test.go
Hello,
I have created a public method StartSpanFromContext() basically copy of traceIntoContext() and created unit testing.
=> Added basic unit testing for opentracing

wrapper/trace/opentracing/opentracing.go, wrapper/trace/opentracing/opentracing_test.go
Reverts micro/go-plugins#309
This breaks ability to have specific tracer config for each service. If you want to use global tracer and not pass tracer to wrapper, please check provided tracer for nil and if it nil, use global tracer.
=> Revert "use global tracer instead"

broker/stan/stan.go
=> broker stan: fix data race

broker/kafka/context.go, broker/kafka/kafka.go, broker/kafka/options.go, go.mod
=> Replace deprecated kafka library

wrapper/trace/opentracing/opentracing.go
=> opentracing client wraper implement `Stream()`

broker/stan/context.go, broker/stan/options.go
Provide a way to set native SubscriptionOption for stan broker through server.SubscriberOption
=> Set native SubscriptionOption

server/grpc/grpc.go, server/grpc/util.go
Hopefully this pr and micro/go-micro#488 should resolve micro/go-micro#483
=> Wait()` option now accept *sync.WaitGroup

registry/multi/multi.go, registry/multi/options.go, registry/multi/watcher.go
multi register plugin allows combine multiple registries like dns and mdns, or mdns and gossip
=> add multi registry

broker/stan/stan.go
=> stan: fix data race in Connect()

broker/stan/stan.go, go.mod
=> stan broker, fix race on subscribe

wrapper/trace/opentracing/opentracing.go
Some OT client library (e.g. jaeger-client-go), doesn't apply
`StartSpanOptions` in order. For example, the parent referece in
jaeger is picked for the fist valid one, the latter will not override
it.
Hence, the go-plugins code here should only set parent ref once.
The precedence order here is that: in-boundary context is checked
first, then check the cross-boundary context. This should make sense.
This resolves #367
=> Fix ot parent span issue

wrapper/validator/validator.go
=> add validator wrapper

wrapper/select/version/README.md, wrapper/select/version/version.go
=> add version selector wrapper

registry/zookeeper/watcher.go
fix issue
https://github.com/micro/go-plugins/issues/383
=> fix goroutine leak in zk watcher when watcher stop

registry/consul/consul.go, registry/consul/encoding.go, registry/consul/encoding_test.go, registry/consul/options.go, registry/consul/registry_test.go, registry/consul/watcher.go, registry/consul/watcher_test.go
https://micro.mu/blog/2019/10/04/deprecating-consul.html
=> Add Consul

config/encoder/cue/cue.go, config/encoder/cue/cue_test.go, go.mod, go.sum
@xmlking submitted a PR for the cue encoder but it never made it across here. 
https://github.com/micro/go-micro/pull/725
=> The PR that never was from @xmlking

registry/zookeeper/watcher.go
=> fix no key watchers for exists nodes when watching a specific service

broker/kafka/context.go, broker/kafka/options.go, broker/nats/context.go, broker/rabbitmq/context.go, broker/snssqs/context.go
=> provide setServerSubscriberOption to brokers

.golangci.yml, .travis.yml
=> add golanglint-ci

wrapper/monitoring/victoriametrics/README.md, wrapper/monitoring/victoriametrics/victoriametrics.go, wrapper/monitoring/victoriametrics/victoriametrics_test.go
=> add victoria metrics monitoring wrapper

broker/mqtt/mqtt.go, broker/nsq/nsq.go, broker/proxy/proxy.go, broker/rabbitmq/rabbitmq.go, broker/stan/stan.go, codec/bsonrpc/codec.go, config/source/configmap/util.go, config/source/vault/util.go, go.mod, go.sum, registry/eureka/marshalling.go, registry/gossip/gossip.go, registry/kubernetes/kubernetes.go, registry/zookeeper/watcher.go, registry/zookeeper/zookeeper.go, store/consul/consul.go, store/memcached/memcached.go, store/redis/redis.go, transport/nats/nats.go, wrapper/ratelimiter/ratelimit/ratelimit_test.go
=> linting fixes, go.mod fixes

registry/zookeeper/zookeeper.go
=> fixes overallocations

broker/sqs/sqs.go
=> fix sqs message binary format

config/source/configmap/configmap.go, config/source/consul/consul.go, config/source/grpc/grpc.go, config/source/mucp/mucp.go, config/source/pkger/pkger.go, config/source/runtimevar/runtimevar.go, config/source/url/url.go
all source have no Write method.
=> Fix all config plugins' source implements

config/source/vault/vault.go
=> add missing interface method to vault source

.travis/tests.sh
=> run tests in parallel

micro/auth/auth.go, micro/auth/go.mod, micro/auth/go.sum, micro/cors/cors.go, micro/disable_rpc/disable_rpc.go, micro/gzip/gzip.go, micro/header/header.go, micro/index/index.go, micro/ip_whitelist/ip_whitelist.go, micro/metadata/metadata.go, micro/metrics/go.mod, micro/metrics/go.sum, micro/metrics/metrics.go, micro/stats_auth/stats_auth.go, micro/whitelist/whitelist.go
Fixed the micro plugins to work with go-micro v2 (i.e. breaking changes)
=> Align micro plugins to v2 changes

registry/zookeeper/watcher.go
`zw.stop`  and `rsp := <-zw.respChan` two can meet the conditions when `watcher` is stop and error `zk: node does not exist` return,  then `select` statement will random pick one condition to execute.
if `rsp := <-zw.respChan` case is picked, `zw.results <- result{nil, err}` will be blocked because no one will read `zw.results`.  so double check if need before write result to `zw.results`
=> fix routine leaks when stop watcher and no node exist error return  

wrapper/trace/opencensus/go.mod, wrapper/trace/opencensus/go.sum, wrapper/trace/opencensus/opencensus.go
=> fix opencensus wrapper with never micro

logger/logrus/go.mod, logger/logrus/go.sum, logger/logrus/logrus.go, logger/zap/go.mod, logger/zap/go.sum, logger/zap/zap.go, logger/zerolog/go.mod, logger/zerolog/go.sum, logger/zerolog/zerolog.go, registry/gossip/gossip_test.go
=> fixup logger for latest go-micro

broker/kafka/options.go
=> broker/kafka: log subscriber error

logger/zap/zap.go
=> logger/zap: fix invalid field allocation

logger/zap/options.go, logger/zap/zap.go
=> fix zaplogger field duplication

logger/zap/zap.go
=> clone zap on fields

broker/kafka/kafka.go
=> broker/kafka: fix closed group error logger

broker/kafka/kafka.go
=> broker/kafka: small code optimization

broker/kafka/options.go
=> only log error if error handler is nil

store/consul/consul.go, store/memcached/memcached.go, store/mysql/mysql.go, store/redis/redis.go
=> store: fix for never go-micro

broker/segmentio/go.mod, broker/segmentio/go.sum, broker/segmentio/kafka.go, broker/segmentio/kafka_test.go
=> broker/segmentio: parallel partition processing

wrapper/monitoring/prometheus/prometheus.go, wrapper/monitoring/prometheus/prometheus_test.go
=> wrapper/monitoring/prometheus: use default registry

wrapper/select/version/version.go
=> wrapper/select/version: fix panic

broker/snssqs/context.go, broker/snssqs/options.go, broker/snssqs/snssqs.go
=> snssqs: add validate on publish options to client publish

store/redis/redis.go
whtn I run auth server, I want to use redis store instead of memory store.
```
func init() {
ccmd.DefaultStores["redis"] = func(opts ...store.Option) store.Store {
return redis.NewStore(
store.Nodes("127.0.0.1:6379"),
)
}
fmt.Println(ccmd.DefaultStores)
}
func main() {
cmd.Init()
}
go run main.go --store=redis store
```
but work wrong.
github.com/micro/micro/v2@v2.9.1/service/auth/handler/auth/auth.go:282
```
278:	func (a *Auth) refreshTokenForAccount(ctx context.Context, id string) (string, error) {
279:		ns := namespace.FromContext(ctx)
280:		prefix := strings.Join([]string{storePrefixRefreshTokens, ns, id, ""}, joinKey)
281:
=> 282:		recs, err := a.Options.Store.Read(prefix, store.ReadPrefix())
```
this is prefix query not key query. so I fix the bug.
it's work on go micro 2.9.0!
=> fix bug https://github.com/micro/go-plugins/issues/565

logger/zerolog/zerolog.go
based on: https://github.com/rs/zerolog/issues/91
=> fix(#487): set CallerSkipFrameCount

logger/zerolog/README.md
=> Update zerolog README.md

broker/nsq/nsq.go
=> nsq broker publish may cause panic sometimes.

logger/logrus/README.md
- Fixed the usage of logger.Infof function.
- While already at it, fixed some indentations.
=> Small fix to logrus README
