registry/etcd/etcd.go

When registry is empty will return registry.ErrNotFound.

Fix when registry is empty will cause panic

---

registry/etcd/etcd.go

I use etcd 2.2.5 with docker. It will happen sometimes when i query other service node. The etcd server doesn't refresh dir ttl time, but don't know is refreshed in other version.
So I suggest removed it temporary.

Fixed: Sometimes etcd get service list is error.

---

registry/zookeeper/util.go
registry/zookeeper/watcher.go
registry/zookeeper/zookeeper.go

#17 I've started working on a zookeeper registry.
Everything seems to work, but some more testing may be necessary.
The watcher code is also a little bit complicated because zookeeper doesn't handle recursive watch and treats node and directory watches differently.

zookeeper registry

---

registry/kubernetes/README.md
registry/kubernetes/client/api/request.go
registry/kubernetes/client/client.go
registry/kubernetes/client/kubernetes.go
registry/kubernetes/client/mock/kubernetes.go
registry/kubernetes/client/mock/utils.go
registry/kubernetes/client/watch/body.go
registry/kubernetes/client/watch/watch.go
registry/kubernetes/client/watch/watch_test.go
registry/kubernetes/kubernetes.go
registry/kubernetes/kubernetes_test.go
registry/kubernetes/watcher.go

This drastically simplifies the registry and is probably closer to what @asim had in mind.
The main difference is that this version only touches the Pods API. Annotations are stored on the pods, with the ability to have multiple services running inside a single pod. No more K8s Services or Endpoints.
This also fixes some bugs from the previous version with the watchers.
I wasn't happy with how complicated the current version is and it was sitting right with me. I'm pretty sure I've finished tinkering now, there is only so much registry I can take.

Kubernetes Registry Further improvements - Pods only.

---

registry/eureka/marshalling.go
registry/eureka/marshalling_test.go

Hi Asim, just a few minor changes/additions to `eureka.serviceToInstance`:
* HostName is required
* UniqueID must be concatenation of address and id (see http://bit.ly/1QdWnnt)
* Metadata must have `instanceId` field

Add required instance details in serviceToInstance

---

micro/router/README.md
micro/router/examples/README.md
micro/router/examples/router.go
micro/router/examples/routes.json
micro/router/options.go
micro/router/router.go
micro/router/router_test.go
micro/router/routes.go
micro/router/routes_test.go
micro/router/sort.go
micro/router/sort_test.go

The router plugin is a HTTP handler plugin for the Micro API which enables you to define routes via go-platform/config.

API Router Plugin

---

broker/rabbitmq/connection.go
broker/rabbitmq/connection_test.go

* do not exclude amqps from prefix check
* use TLS dialer for amqps URLs

Fix handling of RabbitMQ URLs that use amqps

---

metrics/prometheus/prometheus.go

The build was broken, since the prometheus client changed.
Still getting the panic `inconsistent label cardinality` when the metrics are used.

updated to changed prometheus client

---

registry/etcdv3/etcdv3.go

When using the prefix parameter, the end of the key value should be added /.
For example, there are two services: rand  and randpro
/micro-registry/rand/rand-08c58afd-9cb1-11e6-9b83-64098063cd81
/micro-registry/randpro/randpro-345af32c-9cb1-11e6-8288-64098063cd81
When the rand service is acquired, it will also contain randpro.

Fix etcdv3 bugs

---

trace/zipkin/zipkin.go

When I initialize the kafka client, an error occurred to me:
kafka: invalid configuration (Producer.Return.Successes must be true to be used in a SyncProducer
So I update the configuration, then it works.

fix a config bug for zipkin initialization

---

broker/rabbitmq/rabbitmq.go

This PR returns the full topic of the message when calling `publication.Topic()`.
`amqp.Delivery` struct contains `RoutingKey` which is essentially the topic name of the message.
When subscribing to wildcard routing keys, it's nice to be able to associate incoming publications to the topic on which the message is emitted, and not the wildcard key.
A quick example:
```go
b := rabbitmq.NewBroker(broker.Addrs("amqp://localhost")
b.Subscribe("events.*", handleMsg, broker.Queue("test")
func handleMsg(p broker.Publication) error {
// On another thread, create a new event with topic: "events.created"
fmt.Println(p.Topic()) // Returns "events.*", but it should really return "events.created"
}
```

Return amqp's Delivery.RoutingKey as RabbitMQ's publication.Topic()

---

sync/consul/leader.go

I run go-plugins/examples/sync/consul/consul.go get **runtime error: invalid memory address or nil pointer dereference**,  below is output 
```
./consul 
[lock:2] attempting to acquire lock
[lock:0] attempting to acquire lock
[lock:1] attempting to acquire lock
[lock:1] acquired lock!
[lock:1] unlocking now
[lock:1] unlocked
[lock:2] acquired lock!
[lock:2] unlocking now
[lock:2] unlocked
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6411d6]
goroutine 28 [running]:
github.com/micro/go-plugins/sync/consul.(*consulLeader).Leader(0xc42014d080, 0x0, 0x0, 0x0)
/usr/local/govendor/src/github.com/micro/go-plugins/sync/consul/leader.go:41 +0x136
main.leader(0x1, 0x7f3580, 0xc4200dd040) …
```

fixed runtime error in go-plugins/examples/sync/consul

---

registry/etcdv3/etcdv3.go
registry/etcdv3/watcher.go

If prev_kv is set, created watcher gets the previous KV before the event happens. If the previous KV is already compacted, nothing will be returned.
fix #108 
remove len(rsp.Kvs) check in GetService
fix GetService retrun err when  len(rsp.Kvs) == 0

registry/etcdv3 get service from prevKv in EventTypeDelete

---

client/grpc/grpc.go

Travis CI already failed before this PR [Build #608](https://travis-ci.org/micro/go-plugins/builds/289931921)
grpc.NewClient( client.Codec(contentType, codec) )  
will cause panic : assignment to entry in nil map

Fix when grpc.NewClient with Codec option will cause panic

---

client/grpc/codec.go
client/grpc/grpc.go
client/grpc/options.go
server/grpc/codec.go
server/grpc/grpc.go
server/grpc/options.go

Add grpc codec options for both client side and server side.
Add a default bytesCodec for grpc client. 
It's useful to transmit bytes of pb message from client to server without marshaling.
It can also receive bytes of pb message without unmarshaling.
Cause it's only a client codec, the server side req and resp are pb message as usual.

Add grpc options for 3rd codec and a default bytesCodec for client

---

wrapper/trace/opentracing/opentracing.go

No longer defering span.Finish() inside the traceIntoContext function, as this prematurely finishes the span, stopping the timer and preventing child spans.
Secondly, in order to allow the code in the wrapped functions to propagate and create sub-spans, we need to create a new context that contains the newly created span.

Minor fixes to the open tracing wrapper.

---

broker/nats/nats.go
broker/nats/nats_test.go
broker/nats/options.go

Hi, 
as discussed on Slack I've re-written the original [PR-136](https://github.com/micro/go-plugins/pull/136). This PR allows to inject a `nats.Options` as `broker.Option`.
I've also extended the existing test to cover the newly added functionality.
If this PR is ok for you, I would add a similar one to nats Registry and Transport.

add option to inject nats.Options in nats Broker

---

registry/nats/nats.go
registry/nats/options.go
registry/nats/options_test.go

Hi, 
in reference to our discussion on Slack, [PR-136](https://github.com/micro/go-plugins/pull/136) and [PR-138](https://github.com/micro/go-plugins/pull/138) I've written this PR which allows to inject nats.Options as registry.Option. 
I incorporates also 3 additional changes: 
- in the method`query(s string, quorum int)` there is a `conn.Subscription`. It's cbHandler times out after a fixed duration set by `DefaultTimeout`. IMHO the timeout should be made changeable and set to `registry.Option.Timeout`.
- a custom WatchTopic can be injected as a `registry.Option`
- a custom QueryTopic can be injected as a `registry.Option`
the custom WatchTopic and QueryTopic are needed to separate two or more groups of services when using the same broker.
I've added unit tests which cover the added …

add option to inject nats.Options in nats Registry

---

transport/nats/nats.go
transport/nats/nats_test.go
transport/nats/options.go

Hi,
in reference to our discussion on Slack, [PR-136](https://github.com/micro/go-plugins/pull/136), [PR-138](https://github.com/micro/go-plugins/pull/138) and [PR-139](https://github.com/micro/go-plugins/pull/139). I've written this PR which allows to inject nats.Options as transport.Option.
In the constructor function `NewTransport()` I've taken cut out the code which checks if the nats address actually has the `nats://` prefix and put it into the function `setAddrs()`. This is now also consistent with the nats Broker and Registry.
I've added unit tests which cover the added code.

add option to inject nats.Options in nats Transport

---

metrics/statsd/statsd.go

I was getting some panics on calls to the `conn` handle when `net.DialTimeout` returned an error, thus also returning `nil` for the `conn` handle. This fix continues to loop through the list of provided statsd server addresses until a successful connection is made before entering into the long-running for-loop that pushes metrics to statsd.
It may or may not be worthwhile to 1) use a back-off approach, and/or 2) only try a certain amount of times before returning from the `run` function altogether.

Handle failed connections to statsd server

---

registry/kubernetes/README.md

This bit me in the ass for a while... especially since I wasn't seeing
the issue locally in minikube. Turns out minikube doesn't enable RBAC by
default! Aargh.

Updated required RBAC ClusterRole verbs to include `watch`

---

broker/sqs/options.go
broker/sqs/sqs.go

This PR has two changes:
1. Removes unused session variable
2. Adds a new broker option to set an instantiated SQS client which will be used instead of creating a new client with shared config state

SQS broker updates

---

micro/cors/cors.go

The existing `header` function was good for adding/allowing custom headers, but we needed a plug-in/solution for customising CORS rules. 
Added plugin, importing the `rs/cors` lib and defining flags to customise allowed headers, methods, and origins.

ADDED CORS plugin

---

server/grpc/extractor.go

added "100.64.0.0/10" to grpc private addresses
Required to support "micro/kubernetes" on shared address space

support shared address space using grpc

---

server/grpc/extractor.go
server/grpc/extractor_test.go
server/grpc/grpc.go
server/http/extractor.go

I've not had a chance to fully test other than "go test" but it seems the extractAddress function is duplicated in a few of the packages and is a near mirror image of the existing Extract function in micro/misc/lib/addr
Not sure what your thought are around moving them to micro/misc/lib/addr and having a dependancy on that package?

move duplicated extractAddress func to micro/misc/lib/addr

---

README.md
wrapper/trace/opencensus/README.md
wrapper/trace/opencensus/opencensus.go

Add simple wrappers for OpenCensus distributed tracing.
I'm quite new to both OpenCensus and go-micro, so feedback is more than welcome.
I don't know how I could efficiently unit test this, do you have a suggestion?
It would be useful to have a review from someone in the OpenCensus team, maybe @rakyll could provide some quick feedback?
Note: my markdown plugin automatically reformatted the main README (I only added a mention to tracing wrappers). Let me know if you want me to revert that.

opencensus: add tracing wrappers

---

wrapper/trace/opencensus/README.md
wrapper/trace/opencensus/opencensus.go
wrapper/trace/opencensus/stats.go
wrapper/trace/opencensus/status.go
wrapper/trace/opencensus/tracker.go

I'm now setting the span status based on the error received.
I also added client and server metrics (non-exhaustive compared to OpenCensus' ochttp and ocgrpc plugins, but it's a start).
Here is a trace where the RPC failed with 404 (status code = 5):
Here is a dashboard I created on GCP from the newly recorded metrics (on a dev environment with no traffic, but we see the metrics look correct):
@rakyll: is using the googleapis error code generated list the recommended way? Is there a more convenient error code mapping exposed somewhere (maybe in opencensus-go) or is it fine for now?
Don't hesitate to suggest anything that would make this PR cleaner/more future-proof if there are things that look clunky.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

opencensus: add error tagging and metrics

---

broker/nats/nats.go
broker/nats/nats_test.go
broker/nats/options.go
registry/nats/nats.go
registry/nats/options.go
registry/nats/options_test.go
registry/nats/watcher.go
transport/nats/nats.go
transport/nats/nats_test.go
transport/nats/options.go

Nats have updated their repo names and breaks the import paths.
`github.com/nats-io/nats` changed to `github.com/nats-io/go-nats`
And their roadmap repo `github.com/nats-io/roadmap` was changed to `github.com/nats-io/nats`

refactor(import): updated to use the new import path for go-nats

---

broker/rabbitmq/connection.go
broker/rabbitmq/rabbitmq.go

- subscriber class is linked with its parent rbrocker to be able to reconnect
- moved resubscrube routine to gorotined subscriber class method (and passed all necessary fields as class fields)
- wait on channel in case of rabbitmq connection loose (at init channel was created and at once closed to simplify code)
- resubscribe in case of rmq connection restore with exp backoff (pulling with sleep from 100ms to 30s, x2 step)

Resubscribe in case of rabbitmq connection failure

---

client/grpc/codec.go
server/grpc/grpc.go
server/http/http.go

- add http server log, inspired by grpc server plugin
- grpc json unmarshal can use number, fix unmarshal Number(8234567890123456789) to interface(8.234567890123457e+18)
- catch grpc status error, this error happen when node grpc client request go-micro grpc server

feat for grpc and http plugins

---

server/grpc/grpc.go

This fixes strange log entry ```grpc: Server.serveStream failed to write status: <nil>```

fix(grpc): Fixed error check

---

selector/shard/shard.go
selector/shard/shard_test.go

Selector strategies should return `ErrNoneAvalable` if no nodes are available otherwise the rest of the code gets real upset and panics as we recently found out in our codebase.
This PR adds the return error when no more nodes are available.
Also test is added to ensure this happens.

Shard selector error on none available

---

broker/rabbitmq/connection.go
broker/rabbitmq/options.go
broker/rabbitmq/rabbitmq.go

This fixes problem when handler returns error and message stucks in prefetch.
Nack calls only when `AutoAck` option is set to false and manual acknowledge is required.

fix(broker-rabbitmq): Add nack for RabbitMQ

---

micro/gzip/gzip.go

If Content-Length header is set, gzip probably writes the wrong number of bytes. We should delete the Content-Length header prior to writing the headers on a gzipped response.
See [https://github.com/golang/go/issues/14975](url) for more context.

gzip middleware fails with Content-Length header

---

client/grpc/grpc.go
client/grpc/options.go

The default maximum received message size is 4 MB.
Resolve #132.

client/grpc: add an option to set maximum received message size

---

server/grpc/grpc.go
server/grpc/options.go

The message size limit affect on receive and send operations.
Default maximum message is equal with upstream (google.golang.com/grpc),
which is 4 MB.

server/grpc: add option to set maximum message size

---

registry/zookeeper/util.go
registry/zookeeper/watcher.go

child node path watched by zookeeper is wrong when zw.wo.Service is set. 
`zk: node does not exist`.
prefix of this child node is `watchPath` not `prefix`.

child node path watched by zookeeper is wrong when zw.wo.Service is set

---

broker/grpc/grpc.go

**Problem**: "_Broker grpc not found_" error when trying to use the build pattern to create a grpc service with grpc broker
**Solution**: add `grpc` to `cmd.DefaultBrokers` on `init`

refactor: add grpc broker to cmd

---

client/grpc/grpc.go
client/grpc/options.go

Continuing patch 99db9b59, where grpc service can received message larger
than their default value (4MB); this commit add option to change the
message size that gRPC client can send.

client/grpc: add option to set maximum send message size

---

broker/gocloud/gocloud.go
broker/gocloud/gocloud_test.go
broker/gocloud/options.go

Support the Go Cloud implementations of pubsub.
Go Cloud (https://github.com/google/go-cloud) is building
cloud-agnostic APIs for a variety of cloud services. We just made our
pubsub API available (https://godoc.org/gocloud.dev/pubsub). We'd like
to integrate it into go-micro.

broker/gocloud: plugin for Go Cloud pubsub

---

README.md
wrapper/monitoring/prometheus/README.md
wrapper/monitoring/prometheus/prometheus.go
wrapper/monitoring/prometheus/prometheus_test.go

Usage:
```
service := micro.NewService(
micro.Name("service name"),
micro.Version("latest"),
micro.WrapHandler(prometheus.NewHandlerWrapper()),
)
service.Init()
```
This handler will export two metrics to prometheus:
* **go_micro_requests_total**. How many go-miro requests processed, partitioned by method and status.
* **go_micro_request_durations_microseconds**. Service method request latencies in microseconds, partitioned by method.

Add prometheus wrapper to gather requests processed and request latencies metrics 

---

wrapper/monitoring/prometheus/prometheus.go
wrapper/monitoring/prometheus/prometheus_test.go

Summary metric type gives meaningful information only for a single instance, while the Histogram allows to make aggregations across multiple nodes of the scalable microservice.
Metric names are changed to more common pattern.

add histogram metric type and use more common metrics naming

---

wrapper/monitoring/prometheus/prometheus.go
wrapper/monitoring/prometheus/prometheus_test.go

this allow to filter by label all metrics, not only own but also default

wrapper: prometheus attach labels to all metrics

---

broker/rabbitmq/auth.go
broker/rabbitmq/connection.go
broker/rabbitmq/connection_test.go
broker/rabbitmq/options.go
broker/rabbitmq/rabbitmq.go

This adds support for RabbitMQ External Authenthication (See https://www.rabbitmq.com/authentication.html) through a `broker.Option`
Since the authentication configuration is a field on the `amqp.Config` which is outside the `tls.Config` which was passed in, in most connect methods, I changed their signature to take in an `amqp.Confg` instead allowing for easier future support of other rabbit features.
To be able to set the `amqp.Config` the dial library now calls `amqp.DialConfig` instead and tests have been changed accordingly.

Added support for RabbitMQ External Authentication

---

broker/rabbitmq/channel.go
broker/rabbitmq/connection.go
broker/rabbitmq/connection_test.go
broker/rabbitmq/options.go
broker/rabbitmq/rabbitmq.go

This adds support for making a Durable Exchange in RabbitMQ through a `broker.Option`
Since the method declaring the exchange does not have access to the broker context, I changed the internal exchange call to be a struct which contains both the name and whether the exchange should be durable or not and expose a new `broker.Option` to set that

Rabbitmq durableexchange

---

server/grpc/README.md
server/grpc/grpc.go
server/grpc/options.go

- Updated grpc README.md to reflect issue with passing server/client options before setting server
- Added custom grpc options support. This also adds support for [grpc middleware](https://github.com/grpc-ecosystem/go-grpc-middleware)

Added support for custom grpc options

---

wrapper/monitoring/prometheus/prometheus.go

Namespace in counter ops already appends it to all metrics names, so not use hacking Sprintf, and use standard method.

put metrics in own namespace

---

wrapper/trace/opentracing/opentracing.go
wrapper/trace/opentracing/opentracing_test.go

Passing the tracer to wrapper is painful. using globaltracing is much easier.

use global tracer instead

---

broker/grpc/grpc.go

grpc.Dial needs tls by default
error detail:
grpc: no transport security set (use grpc.WithInsecure() explicitly or set credentials)

repair grpc.Dial error

---

broker/kafka/options.go

broker/kafka/kafka.go: Line:54
func (p *publication) Ack() error {
p.sess.MarkMessage(p.km, "")
return nil
}
When missing  p.km ,it will panic

fix broker.Publication.Ack() panic in kafka

---

registry/nats/nats.go
registry/nats/options.go
registry/nats/options_test.go
registry/nats/watcher.go

Hi @asim, 
I saw you updated a few days ago the url for the nets repo for the broker plugin. This PR updates the repo path for the nats registry plugin.

registry/nats: use new repo path

---

transport/nats/nats.go
transport/nats/nats_test.go
transport/nats/options.go

Similar to #340, this PR updates the nats repo path for the transport/nats plugin .

transport/nats: use new repo path

---

broker/stan/options.go
broker/stan/stan.go

1.Provide DurableName options for stan broker
2.Use stan.GetDefaultOptions() instead of stan.DefaultOptions.
For details see https://github.com/nats-io/nats.go/issues/308.

durable subscriptions for nats streaming

---

go.mod
go.sum

currently go.mod refers to `github.com/nats-io/nats.go v1.8.2-0.20190607221125-9f4d16fe7c2d`. This commit is no longer accessible, presumably due to rebasing (see https://github.com/nats-io/nats.go/issues/493 and https://github.com/golang/go/issues/33076). Therefore, we see an [error](https://travis-ci.org/micro/go-plugins/jobs/557940754#L403) in travis-ci: 
`go: github.com/nats-io/nats.go@v1.8.2-0.20190607221125-9f4d16fe7c2d: unknown revision 9f4d16fe7c2d`.
In a local environment, this error might not occur as `modcache` can still have this commit (`GOPROXY=https://proxy.golang.org` also has this commit). 
This commit changes the dependency's version to the latest tag `1.8.1`. 
related to #374

changed version of dependency nats.go

---

broker/snssqs/context.go
broker/snssqs/options.go
broker/snssqs/snssqs.go

This allows you to set aws config options on each service used in the snssqs broker. 
For example, this will allow me to utilize localstack for developing services using AWS locally:
```
snsConfig := &aws.Config{
Endpoint: aws.String(config.Get("aws", "sns", "endpoint").String("")),
}
sqsConfig := &aws.Config{
Endpoint: aws.String(config.Get("aws", "sqs", "endpoint").String("")),
}
stsConfig := &aws.Config{
Endpoint: aws.String(config.Get("aws", "sts", "endpoint").String("")),
}
br := snssqs.NewBroker(
snssqs.SNSConfig(snsConfig),
snssqs.SQSConfig(sqsConfig),
snssqs.STSConfig(stsConfig),
)
```

Add Service Configuration for AWS snssqs broker plugin

---

broker/googlepubsub/googlepubsub.go

if `GOOGLEPUBSUB_PROJECT_ID` is present, it will overwrite programmatically set projectID.
User also have to provide   GOOGLE_APPLICATION_CREDENTIALS=path_to_auth_json.json for Production Environment  or `PUBSUB_EMULATOR_HOST=localhost:8085` when using  google pubsub emulator

Let user set Google ProjectID via Env

---

config/source/configmap/README.md

I add a section on Kubernetes wrights to make configmap works
I add a yaml example that works on my K8S cluster, I think it's generic enough to work on others.

Add a section about Kubernetes wrights

---

broker/rabbitmq/rabbitmq.go

- In the case of "fast produce/ slow consumer ",   user often hope to store messages in RabbitMQ.
- but current implementation will lead to plenty of goroutines,  read all message into memory. If the process crash at that time,  we'll lose many messages.
- with the new implementation,  we leave the choice to the user.  one can always start new goroutines in EventHandler if he wants.
```golang
micro.RegisterSubscriber("foo.bar", srv, func(ctx context.Context, msg *Foo)error{
go dealMessage(msg)
})
```
or keep serial process
```golang
micro.RegisterSubscriber("foo.bar", srv, func(ctx context.Context, msg *Foo)error{
dealMessage(msg)
})
```
this provides more flexibility

receive message with single go routine

---

config/source/configmap/configmap_test.go
config/source/configmap/util.go

This pr is a solution to the issue here: https://github.com/micro/go-plugins/issues/406
The fix changes the split function in the configmap util to only use the first instance of the delimiter so that the entire value after the first is used.
An example would be if a configmap was created as such:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: config
namespace: test
data:
sample: "TEST1=test\nTEST2=te=st"
```
Before the change the resulting values would be:
TEST1='test'
TEST2='te'
And after this change they would be:
TEST1='test'
TEST2='test'

Fix for configmap values that contain '='

---

config/source/pkger/README.md
config/source/pkger/format.go
config/source/pkger/options.go
config/source/pkger/pkger.go
go.mod
go.sum

This plugin enables to bundle config resources along with go binary.
when no `pkged.go`  is found in the source path, this plugin behaves same as `file` source plugin.
when `pkged.go`  is generates, it will use `pkged.go`  for loading the config data instead of the original file source. 
https://blog.gobuffalo.io/introducing-pkger-static-file-embedding-in-go-1ce76dc79c65

adding pkger source plugin for go-config

---

server/http/http.go
server/http/message.go
server/http/subscriber.go

This commit adds missing server.Message fields to httpMessage.

Extend httpMessage to match server.Message signature

---

broker/googlepubsub/googlepubsub.go

I am getting **Quota exceeded** error in the stackdriver logs and realized we are doing `if topic Exists` check for every publish action. 
```
error: "rpc error: code = ResourceExhausted desc = Quota exceeded for quota metric 'Administrator read-only operations' and limit 'Administrator read-only operations per minute' of service 'pubsub.googleapis.com' for consumer 'project_number:11111'." 
```
As per google docs, they recommend *try/catch* and create the topic if needed. 
https://cloud.google.com/pubsub/docs/troubleshooting#admin

Avoid  excessive checks if topic Exists

---

micro/router/routes.go
micro/router/routes_test.go

This changes the strict path matching to prefix based path matching, allowing to configure a reverse proxy for more than just a single page.
It will cause routes at `/` to always match if method and host match, but we have the weight to properly address that. I added a test for that case.
This is not yet regex based matching but it is good enough for me.
Let me know what you think.

Add prefix based path matching to the router

---

micro/router/README.md
micro/router/routes.go

With this I can properly reverse proxy a web page on another machine.
Also adds an `insecure` route option to allow proxying to self signed https endpoints.

Route sub paths and allow insecure certificates

---

logger/logrus/logrus.go
logger/logrus/options.go

Allow to set an existing *logrus.Logger when initializing a new logrusLogger.

Added WithLogger() method to set an existing logrus.Logger.

---

logger/logrus/README.md
logger/logrus/logrus.go
logger/logrus/logrus_test.go
logger/logrus/options.go

- Fix #499 
- Added `func WithLogger(l logrus.StdLogger) logger.Option`. Allow to initialize `Logger` with an existing `*logrus.Logger` or `*logrus.Entry`.

Fix log with fields and log with error

---

logger/logrus/logrus.go

`Error(err error) Logger` has been removed from `go-micro/logger.Logger` interface. Keep updated with it.

logger/logrus: Removed unnecessary Error method

---

broker/rabbitmq/options.go
broker/rabbitmq/rabbitmq.go

Since RabbitMQ version 3.5.0 priority queues are supported - https://www.rabbitmq.com/priority.html
When publishing a message `Priority` property can be set to declare the, well, priority of the message.
This PR adds support for this

Add support for specifying priority when publishing a message to rabbitmq

---

registry/eureka/marshalling.go

the `addr` may append port in which case it would cause invalid address

Fix wrong address format like `192.168.100.18:5495:5495`

---

registry/consul/consul.go

Default consul config make too many connects, and consul has default limits: http_max_conns_per_client=200. 
The service will register fail when you run more then 10 services

refactor: default consul config

---

broker/snssqs/options.go
broker/snssqs/snssqs.go
broker/snssqs/snssqs_test.go

sns/sqs only allow 10 attributes when publishing a message. Due to how we are copying the message header this can be exceeded depending on other parts of go-micro and additional tooling are adding to requests along the way. If you exceed 10 attributes will make its way into sns/sqs and silently fail. Additionally, http2 headers like :authority contain invalid characters for sns/sqs and cause it to fail as well.
So this change allows for the detection of these to cases and additionally adds support for whitelisting header attributes so that users can ensure delivery.

broker snssqs - add header validation and whitelist support

---

registry/consul/encoding.go

when there was many rpc calls decode will use a lot of memeory, so we should close the zlib reader

fix: call Close on the zlib ReadCloser when done

---

wrapper/trace/opentracing/opentracing.go

In `metadata.FromContext(ctx)` All keys are titled case using `strings.Title`.  
But 
```
sp.Tracer().Inject(sp.Context(), opentracing.TextMap, opentracing.TextMapCarrier(newMd))
```
only insert SpanID, TraceID in lower-case. This will lead to span information missing issue.

wrapper/trace/opentracing: fix tracing key title case

---

README.md

Hi, after I followed the Usage Instructions, I got errors.  
`go run plugins.go --broker=rabbitmq --registry=kubernetes --transport=nats`
```
2020-06-18 16:51:33.922603 I | WARNING: proto: message go.micro.broker.Empty is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
2020-06-18 16:51:33.922629 I | WARNING: proto: message go.micro.broker.PublishRequest is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
2020-06-18 16:51:33.922649 I | WARNING: proto: message go.micro.broker.SubscribeRequest is already registered
A future release will panic on registration …
```

fix readme import path for v2

---

store/redis/go.mod
store/redis/go.sum
store/redis/redis.go
store/redis/redis_test.go

Added ability to use username and password in the url used to access Redis. 
Users can now use the following types of URLs:
- `redis://<redisHost>:<redisPort>`
- `redis://:<password>@<redisHost>:<redisPort>`
- `redis://username:<password>@<redisHost>:<redisPort>`
For backwards compatibility, users can still use:
- `<redisHost>:<redisPort>`
Also upgraded the Redis client package used from version  5 to version 7. 
Finally, added some rudimentary tests.

Added ability to use username and password in Redis url 

---

registry/zookeeper/util.go

update zookeeper createPath flag 0 to 1,if we use it to registe service,should use ephemeral node not persisent node

update zookeeper createPath flag 0 to 1

---

broker/rabbitmq/channel.go
broker/rabbitmq/connection.go

Use cases
rabbitmqDelay.DefaultRabbitURL = os.Getenv("RABBIT_URL")
args := make(amqp.Table)
args["x-delayed-type"] = "direct"
rabbitmqDelay.DefaultExchange = rabbitmqDelay.Exchange{Name: exchangeDelay, Kind: "x-delayed-message", Args: args}
DelayBroker := rabbitmqDelay.NewBroker(rabbitmqDelay.DurableExchange())
Publish
body, _ := proto.Marshal(resp.ExamRecord)
if err := DelayBroker.Publish(AutomaticHandingInTopic, &broker.Message{
Header: map[string]string{"x-delay":"60000"},
Body: body,
}, rabbitmqDelay.DeliveryMode(2)); err != nil {
resp.Error = &pb.Error{Description: err.Error()}
}

Delayed message support
